name = "techjobmarket-us"
compatibility_date = "2024-11-01"

[[routes]]
pattern = "techjobmarket.com"
custom_domain = true

[[routes]]
pattern = "www.techjobmarket.com"
custom_domain = true

[observability]
enabled = true
